// Returns active Metro bus routes from a statically baked list.
//
// Why static: Metro's public API has no single /routes endpoint. The previous
// approach made 91 parallel route_overview calls per cache miss, causing
// intermittent timeouts that baked empty names into the 24h CDN cache.
//
// To refresh this list (e.g. Metro adds/removes a route or changes a name):
//   node api/scripts/fetch-routes.js
// then paste the output ROUTES array here.
//
// Validated against Metro's API 2026-05-23. All bus routes share color #E16710.
// Fields: code, short (arterials), t1/t2 (terminal stop names for endpoint display),
//         name (full description for page titles and search).

const ROUTES = [
  { code:'2',   short:'Sunset Bl',                                              t1:'Westwood', t2:'USC', name:'USC - Westwood via Sunset Bl' },
  { code:'4',   short:'Santa Monica Bl',                                        t1:'Santa Monica', t2:'Downtown LA', name:'Downtown LA - Santa Monica via Santa Monica Bl' },
  { code:'10',  short:'Temple St, Melrose Av',                                  t1:'West Hollywood', t2:'Downtown LA', name:'Northbound to DTLA-Southbound to Avalon Station' },
  { code:'14',  short:'Beverly Bl',                                             t1:'Cedars Sinai Medical Center', t2:'Downtown LA', name:'Eastbound to DTLA-Westbound to Cedars-Sinai' },
  { code:'16',  short:'West 3rd St',                                            t1:'West Hollywood', t2:'Downtown LA', name:'Downtown LA - West Hollywood via West 3rd St' },
  { code:'18',  short:'6th St, Whittier Bl',                                    t1:'Wilshire/Western Station', t2:'Montebello Metrolink Station', name:'Wilshire Western Station - Montebello Metrolink Station via 6th St-Whittier Bl' },
  { code:'20',  short:'Wilshire Bl',                                            t1:'Westwood/Santa Monica', t2:'Downtown LA', name:'Downtown LA - Westwood/Santa Monica via Wilshire Bl' },
  { code:'28',  short:'Olympic Bl',                                             t1:'Century City', t2:'Downtown LA', name:'Century City - Downtown LA via Olympic Bl' },
  { code:'30',  short:'Pico Bl',                                                t1:'Pico Rimpau Transit Center', t2:'Little Tokyo Station', name:'Pico Rimpau Transit Center - Downtown LA - Indiana Station via Pico Bl & 1st St' },
  { code:'33',  short:'Venice Bl',                                              t1:'Santa Monica', t2:'Downtown LA', name:'Downtown LA - Santa Monica via Venice Bl' },
  { code:'35',  short:'Washington Bl',                                          t1:'Downtown LA', t2:'Washington/Fairfax Transit Hub', name:'Eastbound to DTLA-Westbound to Washington/Fairfax via Washington Bl' },
  { code:'37',  short:'Adams Bl',                                               t1:'Downtown LA', t2:'Washington/Fairfax', name:'Eastbound to DTLA-Westbound to Cedars-Sinai' },
  { code:'38',  short:'Jefferson Bl',                                           t1:'Washington/Fairfax', t2:'Downtown LA', name:'Eastbound to DTLA-Westbound to Washington/Fairfax via Washington Bl' },
  { code:'40',  short:'MLK Bl, Hawthorne Bl',                                   t1:'South Bay/Redondo Beach Transit Center', t2:'Downtown LA', name:'Downtown LA - South Bay Galleria via ML King Bl-Hawthorne Bl' },
  { code:'45',  short:'Broadway',                                               t1:'Harbor Freeway Station', t2:'Lincoln Heights', name:'Lincoln Heights - Downtown LA - Harbor Freeway Station via Broadway' },
  { code:'48',  short:'Main St, South San Pedro St',                            t1:'Downtown LA', t2:'Avalon Station', name:'Northbound to DTLA-Southbound to Avalon Station' },
  { code:'51',  short:'7th St, Avalon Bl',                                      t1:'CSU Dominguez Hills', t2:'Westlake/MacArthur Park Station', name:'Westlake/MacArthur Park Station - Downtown LA - CSU Dominguez Hills via 7th St-Avalon Bl' },
  { code:'53',  short:'Central Av',                                             t1:'CSU Dominguez Hills', t2:'Downtown LA', name:'Downtown LA - Willowbrook/Rosa Parks Station - CSU Dominguez Hills via Central Av' },
  { code:'55',  short:'Compton Av',                                             t1:'Willowbrook/Rosa Parks Station', t2:'Downtown LA', name:'Downtown LA - Willowbrook/Rosa Parks Station via Compton Av' },
  { code:'60',  short:'Long Beach Bl',                                          t1:'Artesia Station', t2:'Downtown LA', name:'Downtown LA - Artesia Station via Long Beach Bl' },
  { code:'62',  short:'Telegraph Rd',                                           t1:'Hawaiian Gardens', t2:'Downtown LA', name:'Downtown LA - Hawaiian Gardens via Telegraph Rd' },
  { code:'66',  short:'8th St, Olympic Bl',                                     t1:'Wilshire Center', t2:'Montebello Metrolink Station', name:'Wilshire Center - Downtown LA - Montebello via 8th St - Olympic Bl' },
  { code:'70',  short:'Cesar Chavez Av, Atlantic Bl, Garvey Av',                t1:'Downtown LA', t2:'El Monte', name:'Downtown LA - El Monte via Cesar Chavez Av-Atlantic Bl-Garvey Av' },
  { code:'74',  short:'Garvey Av, 1st Av',                                      t1:'Monterey Park', t2:'Montebello', name:'Monterey Park - Cal State LA - LA Union Station - Little Tokyo - Montebello via Garvey Av & 1st St' },
  { code:'76',  short:'Valley Bl',                                              t1:'Downtown LA', t2:'El Monte', name:'Downtown LA - El Monte via Valley Bl' },
  { code:'78',  short:'Las Tunas Av, Huntington Dr',                            t1:'Downtown LA', t2:'Arcadia', name:'Downtown LA - Arcadia via Las Tunas Av & Huntington Dr' },
  { code:'81',  short:'Figueroa St',                                            t1:'Eagle Rock', t2:'Harbor Freeway Station', name:'Eagle Rock - Downtown LA - Harbor Freeway Station via Figueroa St' },
  { code:'90',  short:'Glendale Av, Foothill Bl, Vineland Av',                  t1:'Downtown LA', t2:'North Hollywood', name:'LA Civic Center - Sunland - North Hollywood via Glendale Av-Foothill Bl-Vineland Av' },
  { code:'92',  short:'Glendale Bl, Glenoaks Bl',                               t1:'Downtown LA', t2:'Sylmar Station', name:'Downtown LA - Sylmar Station via Glendale-Glenoaks Bl' },
  { code:'93',  short:'San Fernando Rd, Rampart Bl, Hoover St',                 t1:'Glendale Galleria', t2:'Grand/LATTC Station', name:'Metro Local Line' },
  { code:'94',  short:'San Fernando Rd, Magnolia Bl',                           t1:'Downtown LA', t2:'North Hollywood', name:'Downtown LA - Glendale - Burbank - North Hollywood via San Fernando Rd-Magnolia Bl' },
  { code:'102', short:'La Tijera Bl, Exposition Bl',                            t1:'LAX City Bus Center', t2:'South Gate', name:'LAX City Bus Center - South Gate via La Tijera-Exposition Bl' },
  { code:'105', short:'La Cienega Bl, Vernon Av',                               t1:'Vernon', t2:'West Hollywood', name:'West Hollywood - Vernon via La Cienega Bl-Vernon Av' },
  { code:'106', short:'Garvey Av, 1st Av',                                      t1:'Monterey Park', t2:'Montebello', name:'Monterey Park - Cal State LA - LA Union Station - Little Tokyo - Montebello via Garvey Av & 1st St' },
  { code:'108', short:'Slauson Av',                                             t1:'Marina Del Rey', t2:'Pico Rivera', name:'Marina Del Rey - Pico Rivera via Slauson Av' },
  { code:'110', short:'Jefferson Bl, Gage Av',                                  t1:'Playa Vista', t2:'Bell Gardens', name:'Playa Vista - Bell Gardens via Jefferson Bl-Gage Av' },
  { code:'111', short:'Florence Av',                                            t1:'LAX City Bus Center', t2:'Norwalk Station', name:'LAX City Bus Center - Norwalk Station via Florence Av' },
  { code:'115', short:'Manchester Av, Firestone Bl',                            t1:'Playa Del Rey', t2:'Norwalk', name:'Playa Del Rey - Norwalk via Manchester Av - Firestone Bl' },
  { code:'117', short:'Century Bl, Imperial Hwy',                               t1:'LAX City Bus Center', t2:'Downey', name:'LAX City Bus Center - Downey via Century Bl-Imperial Hwy' },
  { code:'120', short:'Imperial Hwy',                                           t1:'Aviation/LAX Station', t2:'Whittwood Center', name:'Aviation/LAX Station - Whittwood Center via Imperial Hwy' },
  { code:'125', short:'Rosecrans Av',                                           t1:'El Segundo', t2:'Norwalk Station', name:'El Segundo - Norwalk Station via Rosecrans Av' },
  { code:'127', short:'Compton Bl, Broadway',                                   t1:'Harbor Freeway Station', t2:'Downey', name:'Harbor Freeway Station - Comption Station - Downey via Compton Bl-Broadway' },
  { code:'128', short:'Alondra Bl',                                             t1:'Compton Station', t2:'Cerritos Towne Center', name:'Compton Station - Cerritos Towne Center via Alondra Bl' },
  { code:'134', short:'Pacific Coast Hwy',                                      t1:'Downtown Santa Monica Station', t2:'Malibu', name:'Eastbound-Downtown Santa Monica Station-Westbound to Malibu' },
  { code:'150', short:'Topanga Canyon Bl, Ventura Bl',                          t1:'Chatsworth', t2:'Encino', name:'Chatsworth - Canoga Park - Tarzana via Topanga Canyon Bl-Ventura Bl' },
  { code:'152', short:'Roscoe Bl',                                              t1:'West Hills Medical Center', t2:'North Hollywood Station', name:'West Hills Medical Center - North Hollywood Station via Roscoe Bl' },
  { code:'154', short:'Oxnard St, Burbank Bl',                                  t1:'Van Nuys', t2:'Burbank Station', name:'Sepulveda Bl - Burbank Station via Oxnard St-Burbank Bl' },
  { code:'155', short:'Riverside Dr, Olive St',                                 t1:'Burbank Station', t2:'North Hollywood Station', name:'Sherman Oaks - Burbank Station via Riverside Dr-Olive St' },
  { code:'158', short:'Devonshire, Woodman',                                    t1:'Chatsworth Station', t2:'Sherman Oaks', name:'Chatsworth Station - Sherman Oaks via Devonshire-Woodman' },
  { code:'161', short:'Westlake Village, Agoura Hills, Calabasas',              t1:'Thousand Oaks', t2:'Canoga Station', name:'Thousand Oaks - Agoura Hills - Calbasas - Warner Center' },
  { code:'162', short:'Sherman Wy, Vineland Av',                                t1:'Woodland Hills', t2:'North Hollywood', name:'Woodland Hills - West Hills - North Hollywood via Sherman Way-Vineland Av' },
  { code:'164', short:'Victory Bl',                                             t1:'West Hills', t2:'Burbank', name:'West Hills - Burbank via Victory Bl' },
  { code:'165', short:'Vanowen St',                                             t1:'West Hills', t2:'Burbank', name:'West Hills - Burbank via Vanowen St' },
  { code:'166', short:'Nordhoff St, Osborne St',                                t1:'Chatsworth', t2:'Sun Valley', name:'Canoga Av - Sun Valley via Nordhoff St-Osborne St' },
  { code:'167', short:'Plummer, Coldwater Canyon',                              t1:'Chatsworth Station', t2:'Studio City', name:'Chatsworth Station - Studio City via Plummer-Coldwater Canyon' },
  { code:'169', short:'Valley Circle, Saticoy St',                              t1:'Warner Center', t2:'Burbank Airport', name:'Warner Center - Burbank Airport via Valley Circle-Saticoy St' },
  { code:'177', short:'I-210, Del Mar Bl',                                      t1:'Pasadena (Caltech)', t2:'JPL', name:'JPL - Pasadena (Caltech)' },
  { code:'179', short:'Huntington Dr',                                          t1:'Rose Hill Transit Center', t2:'Arcadia', name:'Rose Hill Transit Center - Arcadia via Huntington Dr' },
  { code:'180', short:'Los Feliz Bl, Colorado Bl',                              t1:'Hollywood', t2:'Pasadena', name:'Hollywood - Glendale - Pasadena via Los Feliz-Colorado' },
  { code:'182', short:'Fletcher Dr, York Bl',                                   t1:'East Hollywood', t2:'Rose Hill', name:'NorthEast LA - East Hollywood' },
  { code:'202', short:'Willowbrook Av',                                         t1:'Del Amo Station', t2:'Willowbrook', name:'Willowbrook/Rosa Parks Station - Compton - Del Amo Station' },
  { code:'204', short:'Vermont Av',                                             t1:'Vermont/Athens Station', t2:'Hollywood', name:'Hollywood - Athens via Vermont Av' },
  { code:'205', short:'Wilmington Av, Vermont Av',                              t1:'San Pedro', t2:'Willowbrook/Rosa Parks Station', name:'Willowbrook/Rosa Parks Station - San Pedro via Wilmington Av-Vermont Av' },
  { code:'206', short:'Normandie Av',                                           t1:'Vermont/Athens Station', t2:'Hollywood', name:'Hollywood - Athens via Normandie Av' },
  { code:'207', short:'Western Av',                                             t1:'Crenshaw Station', t2:'Hollywood', name:'Hollywood - Athens via Western Av' },
  { code:'209', short:'Van Ness Av, Arlington Av',                              t1:'Crenshaw C Line (Green) Station', t2:'Expo/Crenshaw Station', name:'Expo/Crenshaw Station - Crenshaw C Line (Green) Station via Van Ness Av-Arlington Av' },
  { code:'210', short:'Crenshaw Bl',                                            t1:'South Bay/Redondo Beach Transit Center', t2:'Hollywood/Vine Station', name:'Hollywood/Vine Station - South Bay Galleria via Vine St-Wilshire/Western Station-Crenshaw Bl' },
  { code:'211', short:'Prairie Av',                                             t1:'Redondo Beach', t2:'Inglewood', name:'Inglewood-South Bay Galleria via Prairie Av-Inglewood Av' },
  { code:'212', short:'La Brea Av',                                             t1:'Hawthorne/Lennox Station', t2:'Hollywood/Highland Station', name:'Hollywood/Vine Station - Hawthorne/Lennox Station via La Brea Av' },
  { code:'215', short:'Inglewood Av',                                           t1:'Redondo Beach', t2:'Inglewood', name:'Inglewood-South Bay Galleria via Prairie Av-Inglewood Av' },
  { code:'217', short:'Hollywood Bl, Fairfax Av',                               t1:'La Cienega Station', t2:'Vermont/Sunset Station', name:'Hollywood/Vine Station - La Cienega Station via Hollywood Bl-Fairfax Av' },
  { code:'218', short:'Laurel Canyon Bl, Fairfax Bl',                           t1:'Cedars Sinai Medical Center', t2:'Studio City', name:'Studio City - Cedars Sinai Medical Center via Laurel Canyon Bl-Fairfax Bl' },
  { code:'222', short:'Hollywood Wy, Riverside Dr',                             t1:'Hollywood', t2:'Sun Valley', name:'Lankershim/Tuxford - Burbank Airport - Hollywood via Hollywood Way & Cahuenga Bl' },
  { code:'224', short:'San Fernando Rd, Lankershim Bl',                         t1:'Universal City Station', t2:'Sylmar Station', name:'Sylmar Station - Universal City Station via San Fernando Rd & Lankershim Bl (+ Hollywood Owl service)' },
  { code:'230', short:'Laurel Canyon Bl',                                       t1:'Studio City', t2:'Sylmar Metrolink Station', name:'Sylmar Station - Studio City via Laurel Canyon Bl' },
  { code:'232', short:'Sepulveda Bl, Pacific Coast Hwy',                        t1:'Long Beach', t2:'LAX City Bus Center', name:'LAX City Bus Center - Long Beach - via Sepulveda Bl-Pacific Coast Hwy' },
  { code:'233', short:'Van Nuys Bl',                                            t1:'Sherman Oaks', t2:'Lakeview Terrace', name:'Lake View Terrace - Sherman Oaks via Van Nuys Bl (+ Westside Owl service)' },
  { code:'234', short:'Sepulveda Bl',                                           t1:'Sherman Oaks', t2:'Sylmar', name:'Mission College - Sylmar Station - Sherman Oaks via Sepulveda Bl' },
  { code:'236', short:'Balboa Bl, Rinaldi St',                                  t1:'Encino', t2:'Sylmar Metrolink Station', name:'Sylmar to Encino via Balboa Bl, Rinaldi St, Foothill Bl, Glenoaks Bl' },
  { code:'237', short:'White Oak Av, Rinaldi St, Woodley Av',                   t1:'Encino', t2:'North Hollywood', name:'Encino-Granada Hill-Mission Hills-North Hollywood via White Oak Av-Woodley Av-Chandler' },
  { code:'240', short:'Reseda Bl, Ventura Bl',                                  t1:'Northridge', t2:'Universal/Studio City Station', name:'Northridge - Universal City Station via Reseda Bl-Ventura Bl' },
  { code:'242', short:'Tampa Av',                                               t1:'Tarzana', t2:'Northridge', name:'Devonshire St - Woodland Hills via Tampa Av-Winnetka Av' },
  { code:'243', short:'Winnetka Av',                                            t1:'Woodland Hills', t2:'Chatsworth', name:'Metro Local Line' },
  { code:'244', short:'De Soto Av',                                             t1:'Woodland Hills', t2:'Chatsworth Station', name:'Chatsworth Station - Ventura Bl via De Soto Av' },
  { code:'246', short:'Avalon Bl',                                              t1:'San Pedro', t2:'Harbor Gateway Transit Center', name:'San Pedro - Harbor Gateway Transit Center via Avalon Bl' },
  { code:'251', short:'Soto St',                                                t1:'Long Beach Bl C Line Station', t2:'Eagle Rock', name:'Eagle Rock - Cypress Park - Long Beach Blvd C Line (Green) Station via Eagle Rock Bl-Soto St' },
  { code:'256', short:'Eastern Av, Washington Bl',                              t1:'CalState LA Transit Center', t2:'Sierra Madre Villa Station', name:'CSU LA - Sierra Madre Villa Station via Eastern Ave-Ave 64-Washington Bl' },
  { code:'258', short:'Fremont Av, Eastern Av, York Bl',                        t1:'Paramount', t2:'Highland Park', name:'Highland Park/South Pasadena - Paramount via Fremont Av-Eastern Av' },
  { code:'260', short:'Fair Oaks Av, Atlantic Bl',                              t1:'Willowbrook/Rosa Parks Station', t2:'Pasadena', name:'Pasadena - Artesia Station via Fair Oaks Av-Atlantic Bl' },
  { code:'265', short:'Paramount Bl',                                           t1:'Lakewood Center Mall', t2:'Pico Rivera', name:'Pico Rivera - Lakewood Center Mall via Paramount Bl' },
  { code:'266', short:'Rosemead Bl',                                            t1:'Lakewood Center Mall', t2:'Sierra Madre Villa Station', name:'Sierra Madre Villa Station - Lakewood Center Mall via Rosemead Bl' },
  { code:'267', short:'Del Mar Bl, Temple City Bl',                             t1:'El Monte Station', t2:'Pasadena', name:'Pasadena - El Monte Station via Del Mar Bl-Temple City Bl' },
  { code:'268', short:'Baldwin Av',                                             t1:'El Monte Station', t2:'Sierra Madre Villa Station', name:'Sierra Madre Villa Station - El Monte Station via Baldwin Av' },
  { code:'287', short:'Santa Anita Av',                                         t1:'The Shops at Montebello', t2:'Arcadia Station', name:'El Monte Station - Arcadia Station via Santa Anita Av' },
  { code:'294', short:'San Fernando Rd',                                        t1:'Burbank Station', t2:'Sylmar Metrolink Station', name:'Burbank Station - Sylmar Station via San Fernando Rd' },
  { code:'296', short:'Riverside Dr',                                           t1:'Lincoln/Cypress Station', t2:'Burbank Station', name:'Lincoln Heights/Cypress Station - Burbank Station via Griffith Park Dr' },
  { code:'344', short:'Hawthorne Bl',                                           t1:'Palos Verdes', t2:'Harbor Gateway Transit Center', name:'Harbor Gateway Transit Center - Palos Verdes via Hawthorne Bl' },
  { code:'460', short:'I-110 Freeway, I-105 Freeway',                           t1:'Downtown LA', t2:'Disneyland', name:'Downtown LA - Disneyland via Harbor Transitway-105 Freeway-Norwalk C Line (Green) Station' },
  { code:'487', short:'Downtown LA - Sierra Madre Villa Station - Temple City', t1:'Downtown LA', t2:'Sierra Madre Villa Station', name:'Downtown LA - Sierra Madre Villa Station - Temple City' },
  { code:'489', short:'Downtown LA - Sierra Madre Villa Station - Temple City', t1:'Downtown LA', t2:'Temple City', name:'Downtown LA - Sierra Madre Villa Station - Temple City' },
  { code:'501', short:'SR-134 Freeway',                                         t1:'North Hollywood Station', t2:'Pasadena', name:'North Hollywood - Pasadena Express' },
  { code:'550', short:'Harbor Transitway',                                      t1:'Harbor Gateway Transit Center', t2:'Exposition Park', name:'Exposition Park/USC  Harbor Gateway via Harbor Transitway' },
  { code:'577', short:'I-605 Freeway',                                          t1:'Long Beach VA Medical Center', t2:'El Monte Station', name:'El Monte Station - Long Beach VA Medical Center via I-605 Freeway' },
  { code:'601', short:'Owensmouth Av, Canoga Av, Burbank Bl',                   t1:'Kaiser/Warner Center Corporate Park', t2:'Canoga Station', name:'Warner Center Circulator' },
  { code:'602', short:'Sunset Bl',                                              t1:'Pacific Palisades', t2:'Westwood', name:'Westwood - Pacific Palisades via Sunset Bl' },
  { code:'603', short:'San Fernando Rd, Rampart St, Hoover St',                 t1:'Grand/LATTC Station', t2:'Glendale Galleria', name:'Glendale - Grand Station via San Fernando Rd-Rampart St-Hoover St' },
  { code:'605', short:'LAC+USC Medical Center - Boyle Heights Shuttle',         t1:'Boyle Heights', t2:'LAC+USC Medical Center', name:'LAC+USC Medical Center - Boyle Heights Shuttle' },
  { code:'611', short:'Huntington Park Shuttle',                                t1:'', t2:'', name:'Huntington Park Shuttle' },
  { code:'617', short:'Beverwil Dr, Burton Wy, Robertson Bl',                   t1:'Pico/Robertson', t2:'Culver City Station', name:'Beverly Dr - Burton Wy - Robertson Bl Shuttle' },
  { code:'660', short:'Fair Oaks Av',                                           t1:'Pasadena', t2:'Altadena', name:'Del Mar Station - Altadena via Fair Oaks Shuttle' },
  { code:'662', short:'Lake Av, Los Robles Av, Lincoln Av',                     t1:'', t2:'', name:'Altadena-Pasadena Shuttle' },
  { code:'665', short:'Indiana St, Gage Ave, Eastern',                          t1:'Cal State LA', t2:'Indiana Station', name:'Cal State LA - City Terrace Shuttle' },
  { code:'686', short:'Allen Av',                                               t1:'Pasadena', t2:'Altadena', name:'Altadena - Pasadena via Allen Av' },
  { code:'690', short:'Foothill Bl, Roxford St, San Fernando Rd',               t1:'Sylmar', t2:'Sunland', name:'Sunland-Sylmar' },
  { code:'699', short:'SoFi Stadium Express',                                   t1:'Hawthorne/Lennox Station', t2:'SoFi Stadium', name:'SoFi Stadium Express' },
  { code:'720', short:'Wilshire Bl',                                            t1:'Santa Monica', t2:'Downtown LA', name:'Santa Monica - Downtown LA via Wilshire Bl' },
  { code:'754', short:'Vermont Av',                                             t1:'Vermont/Athens Station', t2:'Hollywood', name:'Hollywood - Athens via Vermont Ave' },
  { code:'761', short:'San Fernando Bl, Van Nuys Bl, Sepulveda Bl',             t1:'Expo/Sepulveda Station', t2:'Sylmar Station', name:'Sylmar Station - E Line (Expo) Line via Van Nuys Bl-Sepulveda Bl' },
];

const COLOR = '#E16710'; // Metro standard orange for all bus routes

export default async function handler(req, res) {
  // No outbound API calls — static data is always fast and consistent.
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate=604800');
  res.json({
    routes: ROUTES.map(r => ({ ...r, color: COLOR })),
  });
}
